---
- name: Test standard shell module
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: "Test shell with output"
      shell: "echo 'Hello from shell!'; sleep 1; echo 'Line 2'; sleep 1; echo 'Done!'"
      register: shell_result
      
    - name: "Show shell result"
      debug:
        var: shell_result 