---
- name: Test live_shell action plugin
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: "Test simple echo"
      live_shell: "echo 'Hello from live_shell!'"
    
    - name: "Test pwd"
      live_shell: "pwd" 