kind: DSCInitialization
apiVersion: dscinitialization.opendatahub.io/v1
metadata:
  name: default-dsci
spec:
  applicationsNamespace: opendatahub
  serviceMesh:
    managementState: Removed
  trustedCABundle:
    customCABundle: ''
    managementState: Managed
