# Build OpenDataHub Operator Tasks
# Ansible task file for building the OpenDataHub operator image from local checkouts

#- name: "Build operator image"
#  live_shell:
#    cmd: "make image-build-custom-registry-local-branch"
#    chdir: "{{ local_checkouts_dir }}/opendatahub-operator"
#    environment:
#      FORK_ORG: "{{ fork_org }}"
#      BRANCH_NAME: "{{ branch_name }}"
#      LOCAL_MODE: "true"
#      LOCAL_CHECKOUTS_DIR: "{{ local_checkouts_dir }}"
#      CUSTOM_REGISTRY_URL: "{{ registry_url }}"
#      CUSTOM_REGISTRY_NAMESPACE: "{{ registry_namespace }}"
#      CUSTOM_REGISTRY_TAG: "{{ registry_tag }}"
#  register: build_result
#

#- debug: var=registry_url
#- debug: var=registry_namespace
#- debug: var=registry_tag
#- fail:

- set_fact:
    image_spec: "{{ registry_url + '/' + registry_namespace + '/opendatahub-operator:' + registry_tag }}"

- name: "Build operator image"
  live_shell:
    cmd: "USE_LOCAL=true make image-build"
    chdir: "{{ local_checkouts_dir }}/opendatahub-operator"
    environment:
      USE_LOCAL: "true"
      IMG: "{{ image_spec }}"
  register: build_result

- name: "Display build results"
  debug:
    msg: "Build completed with return code: {{ build_result.rc }}"
  when: build_result is defined 
