---
# Combined workflow: Build operator image, push to registry, and deploy to cluster
# This combines build.yml, push.yml, pre-deploy.yml, and deploy.yml workflows

- include_tasks: image_build.yml

- include_tasks: image_push.yml

- include_tasks: image_deploy.yml 
