# Build OpenDataHub Operator Tasks
# Ansible task file for building the OpenDataHub operator image from local checkouts

- name: "Check build environment"
  command: "python {{ project_root }}/tool.py show-config"
  register: build_env_check
  
- name: "Display build environment"
  debug:
    var: build_env_check.stdout_lines

- name: "Build operator image"
  shell: "make image-build-custom-registry-local-branch"
  args:
    chdir: "{{ local_checkouts_dir }}/opendatahub-operator"
  environment:
    FORK_ORG: "{{ fork_org }}"
    BRANCH_NAME: "{{ branch_name }}"
    LOCAL_MODE: "true"
    LOCAL_CHECKOUTS_DIR: "{{ local_checkouts_dir }}"
    CUSTOM_REGISTRY_URL: "{{ registry_url }}"
    CUSTOM_REGISTRY_NAMESPACE: "{{ registry_namespace }}"
    CUSTOM_REGISTRY_TAG: "{{ registry_tag }}"
  register: build_result

- name: "Display build results"
  debug:
    msg: "Build completed with return code: {{ build_result.rc }}"
  when: build_result is defined 