# Build, Push, and Deploy OpenDataHub Complete Pipeline
# Ansible task file for the full CI/CD pipeline

- name: "Build OpenDataHub Operator"
  include_tasks: build.yml

- name: "Push OpenDataHub Operator Image"
  include_tasks: push.yml

- name: "Deploy OpenDataHub to Cluster"
  include_tasks: deploy.yml 