# Cleanup, Build, Push, and Deploy OpenDataHub Complete Pipeline
# Ansible task file for the full development cycle with cleanup

- name: "Cleanup OpenDataHub from Cluster"
  include_tasks: cleanup.yml

- name: "Build OpenDataHub Operator"
  include_tasks: build.yml

- name: "Push OpenDataHub Operator Image"
  include_tasks: push.yml

- name: "Deploy OpenDataHub to Cluster"
  include_tasks: deploy.yml 