---
# OpenDataHub deployment task - deploys operator, DSCI, and DSC
# Run pre-deploy.yml first to set up namespaces and dependencies

- name: "Check if operator already deployed"
  live_shell:
    cmd: "kubectl get deployment opendatahub-operator-controller-manager -n opendatahub-operator-system"
  register: check_operator_result
  failed_when: false

- name: "Display operator check result"
  debug:
    msg: "Operator deployment status: {{ 'EXISTS' if check_operator_result.rc == 0 else 'NOT FOUND' }}"

- name: "Deploy operator"
  live_shell:
    cmd: "make deploy"
    chdir: "{{ local_checkouts_dir }}/opendatahub-operator"
    environment:
      IMG: "{{ registry_url }}/{{ registry_namespace }}/odh-operator:{{ registry_tag }}"
  register: deploy_operator_result

- name: "Wait for operator to be ready"
  live_shell:
    cmd: "kubectl wait --for=condition=Available deployment/opendatahub-operator-controller-manager -n opendatahub-operator-system --timeout={{ wait_timeout }}s"
  register: wait_operator_result

- name: "Create DSCI configuration file"
  copy:
    content: |
      apiVersion: dscinitialization.opendatahub.io/v1
      kind: DSCInitialization
      metadata:
        labels:
          app.kubernetes.io/name: dscinitialization
          app.kubernetes.io/instance: default
          app.kubernetes.io/part-of: opendatahub-operator
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/created-by: opendatahub-operator
        name: {{ dsci_config.name }}
      spec:
      {{ dsci_config.spec | to_nice_yaml | indent(2, first=True) }}
    dest: "/tmp/dsci-config.yaml"
  register: create_dsci_config

- name: "Deploy DSCI"
  live_shell:
    cmd: "kubectl apply -f /tmp/dsci-config.yaml -n {{ application_namespace }}"
  register: deploy_dsci_result

# WORKAROUND!!!
#- name: "Apply updated RBAC permissions"
#  live_shell:
#    cmd: "kustomize build config/default | kubectl apply -f -"
#    chdir: "{{ local_checkouts_dir }}/opendatahub-operator"
#  register: apply_rbac_result

# WORKAROUND - we need to fix this permanently with more fine grain perms
- name: "WORKAROUND: fix permissions"
  live_shell:
    cmd: oc adm policy add-cluster-role-to-user cluster-admin -z opendatahub-operator-controller-manager -n opendatahub-operator-system

- name: "Wait for DSCI to be ready"
  live_shell:
    cmd: "kubectl wait --for=condition=Available dscinitializations.dscinitialization.opendatahub.io/{{ dsci_config.name }} -n {{ application_namespace }} --timeout={{ wait_timeout }}s"
  register: wait_dsci_result

- name: "Create DSC configuration file"
  copy:
    content: |
      apiVersion: datasciencecluster.opendatahub.io/v1
      kind: DataScienceCluster
      metadata:
        name: {{ dsc_config.name }}
        labels:
          app.kubernetes.io/name: datasciencecluster
          app.kubernetes.io/instance: default
          app.kubernetes.io/part-of: opendatahub-operator
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/created-by: opendatahub-operator
      spec:
      {{ dsc_config.spec | to_nice_yaml | indent(2, first=True) }}
    dest: "/tmp/dsc-config.yaml"
  register: create_dsc_config

- name: "Deploy DSC"
  live_shell:
    cmd: "kubectl apply -f /tmp/dsc-config.yaml -n {{ application_namespace }}"
  register: deploy_dsc_result

- name: "Wait for DSC to be ready"
  live_shell:
    cmd: "kubectl wait --for=condition=Ready datascienceclusters.datasciencecluster.opendatahub.io/{{ dsc_config.name }} -n {{ application_namespace }} --timeout={{ wait_timeout }}s"
  register: wait_dsc_result

- name: "Check operator status"
  live_shell:
    cmd: "kubectl get deployment opendatahub-operator-controller-manager -n opendatahub-operator-system"
  register: final_operator_status

- name: "Check DSC status"
  live_shell:
    cmd: "kubectl get datascienceclusters.datasciencecluster.opendatahub.io -n {{ application_namespace }}"
  register: final_dsc_status

- name: "Clean up temporary files"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/dsci-config.yaml"
    - "/tmp/dsc-config.yaml"
  register: cleanup_result

- name: "OpenDataHub deployment complete"
  debug:
    msg:
      - "✅ OpenDataHub deployment completed successfully!"
      - ""
      - "🔧 Configuration Summary:"
      - "Operator Namespace: opendatahub-operator-system"
      - "Target Namespace: {{ application_namespace }}"
      - ""
      - "📋 Resources Created:"
      - "✓ DSC Initialization: {{ dsci_config.name }}"
      - "✓ Data Science Cluster: {{ dsc_config.name }}"
      - ""
      - "🌐 Next Steps:"
      - "- Verify component status: kubectl get pods -n {{ application_namespace }}"
      - "- Check component logs if needed"
      - "- Access dashboard and workbenches as configured" 
