# Push OpenDataHub Operator Image Tasks
# Ansible task file for pushing the built OpenDataHub operator image to registry

- set_fact:
    image_spec: "{{ registry_url + '/' + registry_namespace + '/opendatahub-operator:' + registry_tag }}"

- name: "Push operator image"
  live_shell:
    cmd: "make image-push"
    chdir: "{{ local_checkouts_dir }}/opendatahub-operator"
    environment:
      IMG: "{{ image_spec }}"
  register: push_result

- name: "Display push results"
  debug:
    msg: "Image push completed with return code: {{ push_result.rc }}"
  when: push_result is defined 
