# Build OpenDataHub Operator Tasks
# Ansible task file for building the OpenDataHub operator image from local checkouts

- name: "Assemble local manifests"
  live_shell:
    cmd: "USE_LOCAL=true ./get_all_manifests.sh"
    chdir: "{{ local_checkouts_dir }}/opendatahub-operator"
