# Build OpenDataHub Operator Tasks
# Ansible task file for building the OpenDataHub operator image from local checkouts

- name: "Assemble local manifests"
  live_shell:
    cmd: "make get-manifests-local"
    chdir: "{{ local_checkouts_dir }}/opendatahub-operator"
    environment:
      FORK_ORG: "{{ fork_org }}"
      BRANCH_NAME: "{{ branch_name }}"
      LOCAL_MODE: "true"
      LOCAL_CHECKOUTS_DIR: "{{ local_checkouts_dir }}"
      CUSTOM_REGISTRY_URL: "{{ registry_url }}"
      CUSTOM_REGISTRY_NAMESPACE: "{{ registry_namespace }}"
      CUSTOM_REGISTRY_TAG: "{{ registry_tag }}"
