# Test Tasks for live_shell action plugin
# Simple test to verify output streaming works

- name: "Test live output with echo"
  live_shell:
    cmd: "echo 'Hello from live_shell action plugin!'"

- name: "Test live output with multiple lines"
  live_shell:
    cmd: "echo 'Line 1'; sleep 1; echo 'Line 2'; sleep 1; echo 'Line 3'"

- name: "Test live output with pwd"
  live_shell:
    cmd: "pwd"

- name: "Test live output with environment"
  live_shell:
    cmd: "echo 'Current user:' && whoami" 