name: "Build OpenDataHub Operator"
description: "Build the OpenDataHub operator image from local checkouts"

steps:
  - name: "Check build environment"
    type: "tool"
    command: "show-config"
    
  - name: "Build operator image"
    type: "shell"
    command: "make image-build-custom-registry-local-branch"
    working_directory: "${LOCAL_CHECKOUTS_DIR}/opendatahub-operator"
    env:
      FORK_ORG: "${FORK_ORG}"
      BRANCH_NAME: "${BRANCH_NAME}"
      LOCAL_MODE: "true"
      LOCAL_CHECKOUTS_DIR: "${LOCAL_CHECKOUTS_DIR}"
      CUSTOM_REGISTRY_URL: "${REGISTRY_URL}"
      CUSTOM_REGISTRY_NAMESPACE: "${REGISTRY_NAMESPACE}"
      CUSTOM_REGISTRY_TAG: "${REGISTRY_TAG}" 